// <auto-generated />
namespace LTQL_1721050441.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_table_NCC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_table_NCC));
        
        string IMigrationMetadata.Id
        {
            get { return "202112210559156_create_table_NCC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
